import { Cities } from './_types';

const AL: Cities = {
  Abbeville: {
    name: 'Abbeville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Adamsville: {
    name: 'Adamsville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Addison: {
    name: 'Addison',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Akron: {
    name: 'Akron',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Alabaster: {
    name: 'Alabaster',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Albertville: {
    name: 'Albertville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Alexander City': {
    name: 'Alexander City',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Aliceville: {
    name: 'Aliceville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Allgood: {
    name: 'Allgood',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Altoona: {
    name: 'Altoona',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Andalusia: {
    name: 'Andalusia',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Anderson: {
    name: 'Anderson',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Anniston: {
    name: 'Anniston',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Arab: {
    name: 'Arab',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Ardmore: {
    name: 'Ardmore',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Argo: {
    name: 'Argo',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Ariton: {
    name: 'Ariton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Arley: {
    name: 'Arley',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Ashford: {
    name: 'Ashford',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Ashland: {
    name: 'Ashland',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Ashville: {
    name: 'Ashville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Athens: {
    name: 'Athens',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Atmore: {
    name: 'Atmore',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Attalla: {
    name: 'Attalla',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Auburn: {
    name: 'Auburn',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Autaugaville: {
    name: 'Autaugaville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Avon: {
    name: 'Avon',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Babbie: {
    name: 'Babbie',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Baileyton: {
    name: 'Baileyton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Bakerhill: {
    name: 'Bakerhill',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Banks: {
    name: 'Banks',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Bay Minette': {
    name: 'Bay Minette',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Bayou La Batre': {
    name: 'Bayou La Batre',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Bear Creek': {
    name: 'Bear Creek',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Beatrice: {
    name: 'Beatrice',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Beaverton: {
    name: 'Beaverton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Belk: {
    name: 'Belk',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Benton: {
    name: 'Benton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Berry: {
    name: 'Berry',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Bessemer: {
    name: 'Bessemer',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Billingsley: {
    name: 'Billingsley',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Birmingham: {
    name: 'Birmingham',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Black: {
    name: 'Black',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Blountsville: {
    name: 'Blountsville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Blue Springs': {
    name: 'Blue Springs',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Boaz: {
    name: 'Boaz',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Boligee: {
    name: 'Boligee',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Bon Air': {
    name: 'Bon Air',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Brantley: {
    name: 'Brantley',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Brent: {
    name: 'Brent',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Brewton: {
    name: 'Brewton',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Bridgeport: {
    name: 'Bridgeport',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Brighton: {
    name: 'Brighton',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Brilliant: {
    name: 'Brilliant',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Brookside: {
    name: 'Brookside',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Brookwood: {
    name: 'Brookwood',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Brundidge: {
    name: 'Brundidge',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Butler: {
    name: 'Butler',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Calera: {
    name: 'Calera',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Camden: {
    name: 'Camden',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Camp Hill': {
    name: 'Camp Hill',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Carbon Hill': {
    name: 'Carbon Hill',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Cardiff: {
    name: 'Cardiff',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Carolina: {
    name: 'Carolina',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Carrollton: {
    name: 'Carrollton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Castleberry: {
    name: 'Castleberry',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Cedar Bluff': {
    name: 'Cedar Bluff',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Center Point': {
    name: 'Center Point',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Centre: {
    name: 'Centre',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Centreville: {
    name: 'Centreville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Chatom: {
    name: 'Chatom',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Chelsea: {
    name: 'Chelsea',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Cherokee: {
    name: 'Cherokee',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Chickasaw: {
    name: 'Chickasaw',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Childersburg: {
    name: 'Childersburg',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Citronelle: {
    name: 'Citronelle',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Clanton: {
    name: 'Clanton',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Clay: {
    name: 'Clay',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Clayhatchee: {
    name: 'Clayhatchee',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Clayton: {
    name: 'Clayton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Cleveland: {
    name: 'Cleveland',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Clio: {
    name: 'Clio',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Coaling: {
    name: 'Coaling',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Coffee Springs': {
    name: 'Coffee Springs',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Coffeeville: {
    name: 'Coffeeville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Coker: {
    name: 'Coker',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Collinsville: {
    name: 'Collinsville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Colony: {
    name: 'Colony',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Columbia: {
    name: 'Columbia',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Columbiana: {
    name: 'Columbiana',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Coosada: {
    name: 'Coosada',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Cordova: {
    name: 'Cordova',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Cottonwood: {
    name: 'Cottonwood',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'County Line': {
    name: 'County Line',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Courtland: {
    name: 'Courtland',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Cowarts: {
    name: 'Cowarts',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Creola: {
    name: 'Creola',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Crossville: {
    name: 'Crossville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Cuba: {
    name: 'Cuba',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Cullman: {
    name: 'Cullman',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Cusseta: {
    name: 'Cusseta',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Dadeville: {
    name: 'Dadeville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Daleville: {
    name: 'Daleville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Daphne: {
    name: 'Daphne',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Dauphin Island': {
    name: 'Dauphin Island',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Daviston: {
    name: 'Daviston',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Dayton: {
    name: 'Dayton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Deatsville: {
    name: 'Deatsville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Decatur: {
    name: 'Decatur',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Demopolis: {
    name: 'Demopolis',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Detroit: {
    name: 'Detroit',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Dodge City': {
    name: 'Dodge City',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Dora: {
    name: 'Dora',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Dothan: {
    name: 'Dothan',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Double Springs': {
    name: 'Double Springs',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Douglas: {
    name: 'Douglas',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Dozier: {
    name: 'Dozier',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Dutton: {
    name: 'Dutton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'East Brewton': {
    name: 'East Brewton',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Eclectic: {
    name: 'Eclectic',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Edwardsville: {
    name: 'Edwardsville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Elba: {
    name: 'Elba',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Elberta: {
    name: 'Elberta',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Eldridge: {
    name: 'Eldridge',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Elkmont: {
    name: 'Elkmont',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Elmore: {
    name: 'Elmore',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Emelle: {
    name: 'Emelle',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Enterprise: {
    name: 'Enterprise',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Epes: {
    name: 'Epes',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Ethelsville: {
    name: 'Ethelsville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Eufaula: {
    name: 'Eufaula',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Eutaw: {
    name: 'Eutaw',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Eva: {
    name: 'Eva',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Evergreen: {
    name: 'Evergreen',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Excel: {
    name: 'Excel',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Fairfield: {
    name: 'Fairfield',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Fairhope: {
    name: 'Fairhope',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Fairview: {
    name: 'Fairview',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Falkville: {
    name: 'Falkville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Faunsdale: {
    name: 'Faunsdale',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Fayette: {
    name: 'Fayette',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Five Points': {
    name: 'Five Points',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Flomaton: {
    name: 'Flomaton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Florala: {
    name: 'Florala',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Florence: {
    name: 'Florence',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Foley: {
    name: 'Foley',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Forkland: {
    name: 'Forkland',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Fort Deposit': {
    name: 'Fort Deposit',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Fort Payne': {
    name: 'Fort Payne',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Franklin: {
    name: 'Franklin',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Frisco City': {
    name: 'Frisco City',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Fruithurst: {
    name: 'Fruithurst',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Fulton: {
    name: 'Fulton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Fultondale: {
    name: 'Fultondale',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Fyffe: {
    name: 'Fyffe',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Gadsden: {
    name: 'Gadsden',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Gainesville: {
    name: 'Gainesville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Gantt: {
    name: 'Gantt',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Garden City': {
    name: 'Garden City',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Gardendale: {
    name: 'Gardendale',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Gaylesville: {
    name: 'Gaylesville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Geiger: {
    name: 'Geiger',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Geneva: {
    name: 'Geneva',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Georgiana: {
    name: 'Georgiana',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Geraldine: {
    name: 'Geraldine',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Gilbertown: {
    name: 'Gilbertown',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Glen Allen': {
    name: 'Glen Allen',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Glencoe: {
    name: 'Glencoe',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Glenwood: {
    name: 'Glenwood',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Goldville: {
    name: 'Goldville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Good Hope': {
    name: 'Good Hope',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Goodwater: {
    name: 'Goodwater',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Gordo: {
    name: 'Gordo',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Gordon: {
    name: 'Gordon',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Gordonville: {
    name: 'Gordonville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Goshen: {
    name: 'Goshen',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Grant: {
    name: 'Grant',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Graysville: {
    name: 'Graysville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Greensboro: {
    name: 'Greensboro',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Greenville: {
    name: 'Greenville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Grimes: {
    name: 'Grimes',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Grove Hill': {
    name: 'Grove Hill',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Guin: {
    name: 'Guin',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Gulf Shores': {
    name: 'Gulf Shores',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Guntersville: {
    name: 'Guntersville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Gurley: {
    name: 'Gurley',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Gu-Win': {
    name: 'Gu-Win',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hackleburg: {
    name: 'Hackleburg',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Haleburg: {
    name: 'Haleburg',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Haleyville: {
    name: 'Haleyville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hamilton: {
    name: 'Hamilton',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hammondville: {
    name: 'Hammondville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hanceville: {
    name: 'Hanceville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Harpersville: {
    name: 'Harpersville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hartford: {
    name: 'Hartford',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hartselle: {
    name: 'Hartselle',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hayden: {
    name: 'Hayden',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hayneville: {
    name: 'Hayneville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Headland: {
    name: 'Headland',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Heath: {
    name: 'Heath',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Heflin: {
    name: 'Heflin',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Helena: {
    name: 'Helena',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Henagar: {
    name: 'Henagar',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Highland Lake': {
    name: 'Highland Lake',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hillsboro: {
    name: 'Hillsboro',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Hobson City': {
    name: 'Hobson City',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hodges: {
    name: 'Hodges',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Hokes Bluff': {
    name: 'Hokes Bluff',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Holly Pond': {
    name: 'Holly Pond',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hollywood: {
    name: 'Hollywood',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Homewood: {
    name: 'Homewood',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hoover: {
    name: 'Hoover',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Horn Hill': {
    name: 'Horn Hill',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hueytown: {
    name: 'Hueytown',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Huntsville: {
    name: 'Huntsville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hurtsboro: {
    name: 'Hurtsboro',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Hytop: {
    name: 'Hytop',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Ider: {
    name: 'Ider',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Indian Springs Village': {
    name: 'Indian Springs Village',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Irondale: {
    name: 'Irondale',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Jackson: {
    name: 'Jackson',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  "Jackson's Gap": {
    name: "Jackson's Gap",
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Jacksonville: {
    name: 'Jacksonville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Jasper: {
    name: 'Jasper',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Jemison: {
    name: 'Jemison',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Kansas: {
    name: 'Kansas',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Kellyton: {
    name: 'Kellyton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Kennedy: {
    name: 'Kennedy',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Killen: {
    name: 'Killen',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Kimberly: {
    name: 'Kimberly',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Kinsey: {
    name: 'Kinsey',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Kinston: {
    name: 'Kinston',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  LaFayette: {
    name: 'LaFayette',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Lake View': {
    name: 'Lake View',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Lakeview: {
    name: 'Lakeview',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Lanett: {
    name: 'Lanett',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Langston: {
    name: 'Langston',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Leeds: {
    name: 'Leeds',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Leesburg: {
    name: 'Leesburg',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Leighton: {
    name: 'Leighton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Lester: {
    name: 'Lester',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Level Plains': {
    name: 'Level Plains',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Lexington: {
    name: 'Lexington',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Libertyville: {
    name: 'Libertyville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Lincoln: {
    name: 'Lincoln',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Linden: {
    name: 'Linden',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Lineville: {
    name: 'Lineville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Lipscomb: {
    name: 'Lipscomb',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Lisman: {
    name: 'Lisman',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Littleville: {
    name: 'Littleville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Livingston: {
    name: 'Livingston',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Loachapoka: {
    name: 'Loachapoka',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Lockhart: {
    name: 'Lockhart',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Locust Fork': {
    name: 'Locust Fork',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Louisville: {
    name: 'Louisville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Lowndesboro: {
    name: 'Lowndesboro',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Loxley: {
    name: 'Loxley',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Luverne: {
    name: 'Luverne',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Lynn: {
    name: 'Lynn',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Madison: {
    name: 'Madison',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Madrid: {
    name: 'Madrid',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Magnolia Springs': {
    name: 'Magnolia Springs',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Malvern: {
    name: 'Malvern',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Maplesville: {
    name: 'Maplesville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Margaret: {
    name: 'Margaret',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Marion: {
    name: 'Marion',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Maytown: {
    name: 'Maytown',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  McIntosh: {
    name: 'McIntosh',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  McKenzie: {
    name: 'McKenzie',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  McMullen: {
    name: 'McMullen',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Memphis: {
    name: 'Memphis',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Mentone: {
    name: 'Mentone',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Midfield: {
    name: 'Midfield',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Midland City': {
    name: 'Midland City',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Midway: {
    name: 'Midway',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Millbrook: {
    name: 'Millbrook',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Millport: {
    name: 'Millport',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Millry: {
    name: 'Millry',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Mobile: {
    name: 'Mobile',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Monroeville: {
    name: 'Monroeville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Montevallo: {
    name: 'Montevallo',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Montgomery: {
    name: 'Montgomery',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Moody: {
    name: 'Moody',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Mooresville: {
    name: 'Mooresville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Morris: {
    name: 'Morris',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Mosses: {
    name: 'Mosses',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Moulton: {
    name: 'Moulton',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Moundville: {
    name: 'Moundville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Mount Vernon': {
    name: 'Mount Vernon',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Mountain Brook': {
    name: 'Mountain Brook',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Mulga: {
    name: 'Mulga',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Munford: {
    name: 'Munford',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Muscle Shoals': {
    name: 'Muscle Shoals',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Myrtlewood: {
    name: 'Myrtlewood',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Napier Field': {
    name: 'Napier Field',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Natural Bridge': {
    name: 'Natural Bridge',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Nauvoo: {
    name: 'Nauvoo',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Nectar: {
    name: 'Nectar',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Needham: {
    name: 'Needham',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'New Brockton': {
    name: 'New Brockton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'New Hope': {
    name: 'New Hope',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'New Site': {
    name: 'New Site',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Newbern: {
    name: 'Newbern',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Newton: {
    name: 'Newton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Newville: {
    name: 'Newville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'North Courtland': {
    name: 'North Courtland',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'North Johns': {
    name: 'North Johns',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Northport: {
    name: 'Northport',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Notasulga: {
    name: 'Notasulga',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Oak Grove': {
    name: 'Oak Grove',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Oak Hill': {
    name: 'Oak Hill',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Oakman: {
    name: 'Oakman',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Odenville: {
    name: 'Odenville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Ohatchee: {
    name: 'Ohatchee',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Oneonta: {
    name: 'Oneonta',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Onycha: {
    name: 'Onycha',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Opelika: {
    name: 'Opelika',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Opp: {
    name: 'Opp',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Orange Beach': {
    name: 'Orange Beach',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Orrville: {
    name: 'Orrville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Owens Cross Roads': {
    name: 'Owens Cross Roads',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Oxford: {
    name: 'Oxford',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Ozark: {
    name: 'Ozark',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Paint Rock': {
    name: 'Paint Rock',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Parrish: {
    name: 'Parrish',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Pelham: {
    name: 'Pelham',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Pell City': {
    name: 'Pell City',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Pennington: {
    name: 'Pennington',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Perdido Beach': {
    name: 'Perdido Beach',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Petrey: {
    name: 'Petrey',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Phenix City': {
    name: 'Phenix City',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Phil Campbell': {
    name: 'Phil Campbell',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Pickensville: {
    name: 'Pickensville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Piedmont: {
    name: 'Piedmont',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Pike Road': {
    name: 'Pike Road',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Pinckard: {
    name: 'Pinckard',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Pine Apple': {
    name: 'Pine Apple',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Pine Hill': {
    name: 'Pine Hill',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Pine Ridge': {
    name: 'Pine Ridge',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Pinson: {
    name: 'Pinson',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Pisgah: {
    name: 'Pisgah',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Pleasant Grove': {
    name: 'Pleasant Grove',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Pleasant Groves': {
    name: 'Pleasant Groves',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Pollard: {
    name: 'Pollard',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Powell: {
    name: 'Powell',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Prattville: {
    name: 'Prattville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Priceville: {
    name: 'Priceville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Prichard: {
    name: 'Prichard',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Providence: {
    name: 'Providence',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Ragland: {
    name: 'Ragland',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Rainbow City': {
    name: 'Rainbow City',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Rainsville: {
    name: 'Rainsville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Ranburne: {
    name: 'Ranburne',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Red Bay': {
    name: 'Red Bay',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Red Level': {
    name: 'Red Level',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Reece City': {
    name: 'Reece City',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Reform: {
    name: 'Reform',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Rehobeth: {
    name: 'Rehobeth',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Repton: {
    name: 'Repton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Ridgeville: {
    name: 'Ridgeville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'River Falls': {
    name: 'River Falls',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Riverside: {
    name: 'Riverside',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Riverview: {
    name: 'Riverview',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Roanoke: {
    name: 'Roanoke',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Robertsdale: {
    name: 'Robertsdale',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Rockford: {
    name: 'Rockford',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Rogersville: {
    name: 'Rogersville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Rosa: {
    name: 'Rosa',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Russellville: {
    name: 'Russellville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Rutledge: {
    name: 'Rutledge',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'St. Florian': {
    name: 'St. Florian',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Samson: {
    name: 'Samson',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Sand Rock': {
    name: 'Sand Rock',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Sanford: {
    name: 'Sanford',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Saraland: {
    name: 'Saraland',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Sardis City': {
    name: 'Sardis City',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Satsuma: {
    name: 'Satsuma',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Scottsboro: {
    name: 'Scottsboro',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Section: {
    name: 'Section',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Selma: {
    name: 'Selma',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Sheffield: {
    name: 'Sheffield',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Shiloh: {
    name: 'Shiloh',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Shorter: {
    name: 'Shorter',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Silas: {
    name: 'Silas',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Silverhill: {
    name: 'Silverhill',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Sipsey: {
    name: 'Sipsey',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Skyline: {
    name: 'Skyline',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Slocomb: {
    name: 'Slocomb',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Smiths Station': {
    name: 'Smiths Station',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Snead: {
    name: 'Snead',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Somerville: {
    name: 'Somerville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'South Vinemont': {
    name: 'South Vinemont',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Southside: {
    name: 'Southside',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Spanish Fort': {
    name: 'Spanish Fort',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Springville: {
    name: 'Springville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Steele: {
    name: 'Steele',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Stevenson: {
    name: 'Stevenson',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Sulligent: {
    name: 'Sulligent',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Sumiton: {
    name: 'Sumiton',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Summerdale: {
    name: 'Summerdale',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Susan Moore': {
    name: 'Susan Moore',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Sweet Water': {
    name: 'Sweet Water',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Sylacauga: {
    name: 'Sylacauga',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Sylvan Springs': {
    name: 'Sylvan Springs',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Sylvania: {
    name: 'Sylvania',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Talladega Springs': {
    name: 'Talladega Springs',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Talladega: {
    name: 'Talladega',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Tallassee: {
    name: 'Tallassee',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Tarrant: {
    name: 'Tarrant',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Taylor: {
    name: 'Taylor',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Thomaston: {
    name: 'Thomaston',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Thomasville: {
    name: 'Thomasville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Thorsby: {
    name: 'Thorsby',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Town Creek': {
    name: 'Town Creek',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Toxey: {
    name: 'Toxey',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Trafford: {
    name: 'Trafford',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Triana: {
    name: 'Triana',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Trinity: {
    name: 'Trinity',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Troy: {
    name: 'Troy',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Trussville: {
    name: 'Trussville',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Tuscaloosa: {
    name: 'Tuscaloosa',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Tuscumbia: {
    name: 'Tuscumbia',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Tuskegee: {
    name: 'Tuskegee',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Twin: {
    name: 'Twin',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Union Grove': {
    name: 'Union Grove',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Union Springs': {
    name: 'Union Springs',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Union: {
    name: 'Union',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Uniontown: {
    name: 'Uniontown',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Valley: {
    name: 'Valley',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Valley Grande': {
    name: 'Valley Grande',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Valley Head': {
    name: 'Valley Head',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Vance: {
    name: 'Vance',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Vernon: {
    name: 'Vernon',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Vestavia Hills': {
    name: 'Vestavia Hills',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Vina: {
    name: 'Vina',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Vincent: {
    name: 'Vincent',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Vredenburgh: {
    name: 'Vredenburgh',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Wadley: {
    name: 'Wadley',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Waldo: {
    name: 'Waldo',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Walnut Grove': {
    name: 'Walnut Grove',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Warrior: {
    name: 'Warrior',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Waterloo: {
    name: 'Waterloo',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Waverly: {
    name: 'Waverly',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Weaver: {
    name: 'Weaver',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Webb: {
    name: 'Webb',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Wedowee: {
    name: 'Wedowee',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'West Blocton': {
    name: 'West Blocton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'West Jefferson': {
    name: 'West Jefferson',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'West Point': {
    name: 'West Point',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Westover: {
    name: 'Westover',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Wetumpka: {
    name: 'Wetumpka',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'White Hall': {
    name: 'White Hall',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Wilsonville: {
    name: 'Wilsonville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Wilton: {
    name: 'Wilton',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Winfield: {
    name: 'Winfield',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Woodland: {
    name: 'Woodland',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Woodstock: {
    name: 'Woodstock',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  Woodville: {
    name: 'Woodville',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  'Yellow Bluff': {
    name: 'Yellow Bluff',
    type: 'Town',
    state: 'Alabama',
    stateInitials: 'AL',
  },
  York: {
    name: 'York',
    type: 'City',
    state: 'Alabama',
    stateInitials: 'AL',
  },
};

export default AL;
