/**
 * @see RESTCountries { @link https://restcountries.com }
 */

type Country = {
  nameUS: string;
  nameBR: string;
  continentUS: string;
  continentBR: string;
  initials: string[];
  countryCode: string;
};

type Countries = {
  [key: string]: Country;
};

const COUNTRIES: Countries = {
  Afghanistan: {
    nameUS: 'Afghanistan',
    nameBR: 'Afeganistão',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['AF', 'AFG'],
    countryCode: '+93',
  },
  Albania: {
    nameUS: 'Albania',
    nameBR: 'Albânia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['AL', 'ALB'],
    countryCode: '+355',
  },
  Algeria: {
    nameUS: 'Algeria',
    nameBR: 'Argélia',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['DZ', 'DZA'],
    countryCode: '+213',
  },
  'American Samoa': {
    nameUS: 'American Samoa',
    nameBR: 'Samoa Americana',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['AS', 'ASM'],
    countryCode: '+1-684',
  },
  Andorra: {
    nameUS: 'Andorra',
    nameBR: 'Andorra',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['AD', 'AND'],
    countryCode: '+376',
  },
  Angola: {
    nameUS: 'Angola',
    nameBR: 'Angola',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['AO', 'AGO'],
    countryCode: '+244',
  },
  Anguilla: {
    nameUS: 'Anguilla',
    nameBR: 'Anguilla',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['AI', 'AIA'],
    countryCode: '+1-264',
  },
  Antarctica: {
    nameUS: 'Antarctica',
    nameBR: 'Ilha Christmas',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['AQ', 'ATA'],
    countryCode: '+672',
  },
  'Antigua and Barbuda': {
    nameUS: 'Antigua and Barbuda',
    nameBR: 'Antígua e Barbuda',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['AG', 'ATG'],
    countryCode: '+1-268',
  },
  Argentina: {
    nameUS: 'Argentina',
    nameBR: 'Argentina',
    continentUS: 'South America',
    continentBR: 'América do Sul',
    initials: ['AR', 'ARG'],
    countryCode: '+54',
  },
  Armenia: {
    nameUS: 'Armenia',
    nameBR: 'Armênia',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['AM', 'ARM'],
    countryCode: '+374',
  },
  Aruba: {
    nameUS: 'Aruba',
    nameBR: 'Aruba',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['AW', 'ABW'],
    countryCode: '+297',
  },
  Australia: {
    nameUS: 'Australia',
    nameBR: 'Austrália',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['AU', 'AUS'],
    countryCode: '+61',
  },
  Austria: {
    nameUS: 'Austria',
    nameBR: 'Áustria',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['AT', 'AUT'],
    countryCode: '+43',
  },
  Azerbaijan: {
    nameUS: 'Azerbaijan',
    nameBR: 'Azerbaijão',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['AZ', 'AZE'],
    countryCode: '+994',
  },
  Bahamas: {
    nameUS: 'Bahamas',
    nameBR: 'Bahamas',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['BS', 'BHS'],
    countryCode: '+1-242',
  },
  Bahrain: {
    nameUS: 'Bahrain',
    nameBR: 'Bahrein',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['BH', 'BHR'],
    countryCode: '+973',
  },
  Bangladesh: {
    nameUS: 'Bangladesh',
    nameBR: 'Bangladesh',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['BD', 'BGD'],
    countryCode: '+880',
  },
  Barbados: {
    nameUS: 'Barbados',
    nameBR: 'Barbados',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['BB', 'BRB'],
    countryCode: '+1-246',
  },
  Belarus: {
    nameUS: 'Belarus',
    nameBR: 'Bielorrússia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['BY', 'BLR'],
    countryCode: '+375',
  },
  Belgium: {
    nameUS: 'Belgium',
    nameBR: 'Bélgica',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['BE', 'BEL'],
    countryCode: '+32',
  },
  Belize: {
    nameUS: 'Belize',
    nameBR: 'Belize',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['BZ', 'BLZ'],
    countryCode: '+501',
  },
  Benin: {
    nameUS: 'Benin',
    nameBR: 'Benim',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['BJ', 'BEN'],
    countryCode: '+229',
  },
  Bermuda: {
    nameUS: 'Bermuda',
    nameBR: 'Bermudas',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['BM', 'BMU'],
    countryCode: '+1-441',
  },
  Bhutan: {
    nameUS: 'Bhutan',
    nameBR: 'Butão',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['BT', 'BTN'],
    countryCode: '+975',
  },
  Bolivia: {
    nameUS: 'Bolivia',
    nameBR: 'Bolívia',
    continentUS: 'South America',
    continentBR: 'América do Sul',
    initials: ['BO', 'BOL'],
    countryCode: '+591',
  },
  'Bosnia and Herzegovina': {
    nameUS: 'Bosnia and Herzegovina',
    nameBR: 'Bósnia e Herzegovina',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['BA', 'BIH'],
    countryCode: '+387',
  },
  Botswana: {
    nameUS: 'Botswana',
    nameBR: 'Botswana',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['BW', 'BWA'],
    countryCode: '+267',
  },
  Brazil: {
    nameUS: 'Brazil',
    nameBR: 'Brasil',
    continentUS: 'South America',
    continentBR: 'América do Sul',
    initials: ['BR', 'BRA'],
    countryCode: '+55',
  },
  'British Indian Ocean Territory': {
    nameUS: 'British Indian Ocean Territory',
    nameBR: 'Território Britânico do Oceano Índico',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['IO', 'IOT'],
    countryCode: '+246',
  },
  'British Virgin Islands': {
    nameUS: 'British Virgin Islands',
    nameBR: 'Ilhas Virgens Britânicas',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['VG', 'VGB'],
    countryCode: '+1-284',
  },
  Brunei: {
    nameUS: 'Brunei',
    nameBR: 'Brunei',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['BN', 'BRN'],
    countryCode: '+673',
  },
  Bulgaria: {
    nameUS: 'Bulgaria',
    nameBR: 'Bulgária',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['BG', 'BGR'],
    countryCode: '+359',
  },
  'Burkina Faso': {
    nameUS: 'Burkina Faso',
    nameBR: 'Burkina Faso',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['BF', 'BFA'],
    countryCode: '+226',
  },
  Burundi: {
    nameUS: 'Burundi',
    nameBR: 'Burundi',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['BI', 'BDI'],
    countryCode: '+257',
  },
  Cambodia: {
    nameUS: 'Cambodia',
    nameBR: 'Camboja',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['KH', 'KHM'],
    countryCode: '+855',
  },
  Cameroon: {
    nameUS: 'Cameroon',
    nameBR: 'Camarões',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['CM', 'CMR'],
    countryCode: '+237',
  },
  Canada: {
    nameUS: 'Canada',
    nameBR: 'Canadá',
    continentUS: 'North America',
    continentBR: 'América do Norte',
    initials: ['CA', 'CAN'],
    countryCode: '+1',
  },
  'Cape Verde': {
    nameUS: 'Cape Verde',
    nameBR: 'Cabo Verde',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['CV', 'CPV'],
    countryCode: '+238',
  },
  'Cayman Islands': {
    nameUS: 'Cayman Islands',
    nameBR: 'Ilhas Cayman',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['KY', 'CYM'],
    countryCode: '+1-345',
  },
  'Central African Republic': {
    nameUS: 'Central African Republic',
    nameBR: 'República Centro-Africana',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['CF', 'CAF'],
    countryCode: '+236',
  },
  Chad: {
    nameUS: 'Chad',
    nameBR: 'Chade',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['TD', 'TCD'],
    countryCode: '+235',
  },
  Chile: {
    nameUS: 'Chile',
    nameBR: 'Chile',
    continentUS: 'South America',
    continentBR: 'América do Sul',
    initials: ['CL', 'CHL'],
    countryCode: '+56',
  },
  China: {
    nameUS: 'China',
    nameBR: 'República Popular da China',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['CN', 'CHN'],
    countryCode: '+86',
  },
  'Christmas Island': {
    nameUS: 'Christmas Island',
    nameBR: 'Austrália',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['CX', 'CXR'],
    countryCode: '+61',
  },
  'Cocos Islands': {
    nameUS: 'Cocos Islands',
    nameBR: 'Austrália',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['CC', 'CCK'],
    countryCode: '+61',
  },
  Colombia: {
    nameUS: 'Colombia',
    nameBR: 'Colômbia',
    continentUS: 'South America',
    continentBR: 'América do Sul',
    initials: ['CO', 'COL'],
    countryCode: '+57',
  },
  Comoros: {
    nameUS: 'Comoros',
    nameBR: 'Comores',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['KM', 'COM'],
    countryCode: '+269',
  },
  'Cook Islands': {
    nameUS: 'Cook Islands',
    nameBR: 'Ilhas Cook',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['CK', 'COK'],
    countryCode: '+682',
  },
  'Costa Rica': {
    nameUS: 'Costa Rica',
    nameBR: 'Costa Rica',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['CR', 'CRI'],
    countryCode: '+506',
  },
  Croatia: {
    nameUS: 'Croatia',
    nameBR: 'Croácia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['HR', 'HRV'],
    countryCode: '+385',
  },
  Cuba: {
    nameUS: 'Cuba',
    nameBR: 'Cuba',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['CU', 'CUB'],
    countryCode: '+53',
  },
  Curacao: {
    nameUS: 'Curacao',
    nameBR: 'Antilhas Holandesas',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['CW', 'CUW'],
    countryCode: '+599',
  },
  Cyprus: {
    nameUS: 'Cyprus',
    nameBR: 'Chipre',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['CY', 'CYP'],
    countryCode: '+357',
  },
  'Czech Republic': {
    nameUS: 'Czech Republic',
    nameBR: 'República Tcheca',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['CZ', 'CZE'],
    countryCode: '+420',
  },
  'Democratic Republic of the Congo': {
    nameUS: 'Democratic Republic of the Congo',
    nameBR: 'Congo-Kinshasa',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['CD', 'COD'],
    countryCode: '+243',
  },
  Denmark: {
    nameUS: 'Denmark',
    nameBR: 'Dinamarca',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['DK', 'DNK'],
    countryCode: '+45',
  },
  Djibouti: {
    nameUS: 'Djibouti',
    nameBR: 'Djibuti',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['DJ', 'DJI'],
    countryCode: '+253',
  },
  Dominica: {
    nameUS: 'Dominica',
    nameBR: 'Dominica',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['DM', 'DMA'],
    countryCode: '+1-767',
  },
  'Dominican Republic': {
    nameUS: 'Dominican Republic',
    nameBR: 'República Dominicana',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['DO', 'DOM'],
    countryCode: '+1-809 +1-829 +1-849',
  },
  'East Timor': {
    nameUS: 'East Timor',
    nameBR: 'Timor-Leste',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['TL', 'TLS'],
    countryCode: '+670',
  },
  Ecuador: {
    nameUS: 'Ecuador',
    nameBR: 'Equador',
    continentUS: 'South America',
    continentBR: 'América do Sul',
    initials: ['EC', 'ECU'],
    countryCode: '+593',
  },
  Egypt: {
    nameUS: 'Egypt',
    nameBR: 'Egito',
    continentUS: 'Africa, Asia',
    continentBR: 'África, Ásia',
    initials: ['EG', 'EGY'],
    countryCode: '+20',
  },
  'El Salvador': {
    nameUS: 'El Salvador',
    nameBR: 'El Salvador',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['SV', 'SLV'],
    countryCode: '+503',
  },
  'Equatorial Guinea': {
    nameUS: 'Equatorial Guinea',
    nameBR: 'Guiné Equatorial',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['GQ', 'GNQ'],
    countryCode: '+240',
  },
  Eritrea: {
    nameUS: 'Eritrea',
    nameBR: 'Eritreia',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['ER', 'ERI'],
    countryCode: '+291',
  },
  Estonia: {
    nameUS: 'Estonia',
    nameBR: 'Estónia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['EE', 'EST'],
    countryCode: '+372',
  },
  Ethiopia: {
    nameUS: 'Ethiopia',
    nameBR: 'Etiópia',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['ET', 'ETH'],
    countryCode: '+251',
  },
  'Falkland Islands': {
    nameUS: 'Falkland Islands',
    nameBR: 'Ilhas Malvinas',
    continentUS: 'South America',
    continentBR: 'América do Sul',
    initials: ['FK', 'FLK'],
    countryCode: '+500',
  },
  'Faroe Islands': {
    nameUS: 'Faroe Islands',
    nameBR: 'Ilhas Féroe',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['FO', 'FRO'],
    countryCode: '+298',
  },
  Fiji: {
    nameUS: 'Fiji',
    nameBR: 'Fiji',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['FJ', 'FJI'],
    countryCode: '+679',
  },
  Finland: {
    nameUS: 'Finland',
    nameBR: 'Finlândia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['FI', 'FIN'],
    countryCode: '+358',
  },
  France: {
    nameUS: 'France',
    nameBR: 'França',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['FR', 'FRA'],
    countryCode: '+33',
  },
  'French Polynesia': {
    nameUS: 'French Polynesia',
    nameBR: 'Polinésia Francesa',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['PF', 'PYF'],
    countryCode: '+689',
  },
  Gabon: {
    nameUS: 'Gabon',
    nameBR: 'Gabão',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['GA', 'GAB'],
    countryCode: '+241',
  },
  Gambia: {
    nameUS: 'Gambia',
    nameBR: 'Gâmbia',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['GM', 'GMB'],
    countryCode: '+220',
  },
  Georgia: {
    nameUS: 'Georgia',
    nameBR: 'Geórgia',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['GE', 'GEO'],
    countryCode: '+995',
  },
  Germany: {
    nameUS: 'Germany',
    nameBR: 'Alemanha',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['DE', 'DEU'],
    countryCode: '+49',
  },
  Ghana: {
    nameUS: 'Ghana',
    nameBR: 'Gana',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['GH', 'GHA'],
    countryCode: '+233',
  },
  Gibraltar: {
    nameUS: 'Gibraltar',
    nameBR: 'Gibraltar',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['GI', 'GIB'],
    countryCode: '+350',
  },
  Greece: {
    nameUS: 'Greece',
    nameBR: 'Grécia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['GR', 'GRC'],
    countryCode: '+30',
  },
  Greenland: {
    nameUS: 'Greenland',
    nameBR: 'Groenlândia',
    continentUS: 'North America',
    continentBR: 'América do Norte',
    initials: ['GL', 'GRL'],
    countryCode: '+299',
  },
  Grenada: {
    nameUS: 'Grenada',
    nameBR: 'Granada',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['GD', 'GRD'],
    countryCode: '+1-473',
  },
  Guam: {
    nameUS: 'Guam',
    nameBR: 'Guam',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['GU', 'GUM'],
    countryCode: '+1-671',
  },
  Guatemala: {
    nameUS: 'Guatemala',
    nameBR: 'Guatemala',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['GT', 'GTM'],
    countryCode: '+502',
  },
  Guernsey: {
    nameUS: 'Guernsey',
    nameBR: 'Guernsey',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['GG', 'GGY'],
    countryCode: '+44-1481',
  },
  Guinea: {
    nameUS: 'Guinea',
    nameBR: 'Guiné',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['GN', 'GIN'],
    countryCode: '+224',
  },
  'Guinea-Bissau': {
    nameUS: 'Guinea-Bissau',
    nameBR: 'Guiné-Bissau',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['GW', 'GNB'],
    countryCode: '+245',
  },
  Guyana: {
    nameUS: 'Guyana',
    nameBR: 'Guiana',
    continentUS: 'South America',
    continentBR: 'América do Sul',
    initials: ['GY', 'GUY'],
    countryCode: '+592',
  },
  Haiti: {
    nameUS: 'Haiti',
    nameBR: 'Haiti',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['HT', 'HTI'],
    countryCode: '+509',
  },
  Honduras: {
    nameUS: 'Honduras',
    nameBR: 'Honduras',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['HN', 'HND'],
    countryCode: '+504',
  },
  'Hong Kong': {
    nameUS: 'Hong Kong',
    nameBR: 'Hong Kong',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['HK', 'HKG'],
    countryCode: '+852',
  },
  Hungary: {
    nameUS: 'Hungary',
    nameBR: 'Hungria',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['HU', 'HUN'],
    countryCode: '+36',
  },
  Iceland: {
    nameUS: 'Iceland',
    nameBR: 'Islândia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['IS', 'ISL'],
    countryCode: '+354',
  },
  India: {
    nameUS: 'India',
    nameBR: 'Índia',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['IN', 'IND'],
    countryCode: '+91',
  },
  Indonesia: {
    nameUS: 'Indonesia',
    nameBR: 'Indonésia',
    continentUS: 'Asia, Oceania',
    continentBR: 'Ásia, Oceania',
    initials: ['ID', 'IDN'],
    countryCode: '+62',
  },
  Iran: {
    nameUS: 'Iran',
    nameBR: 'Irã',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['IR', 'IRN'],
    countryCode: '+98',
  },
  Iraq: {
    nameUS: 'Iraq',
    nameBR: 'Iraque',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['IQ', 'IRQ'],
    countryCode: '+964',
  },
  Ireland: {
    nameUS: 'Ireland',
    nameBR: 'Irlanda',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['IE', 'IRL'],
    countryCode: '+353',
  },
  'Isle of Man': {
    nameUS: 'Isle of Man',
    nameBR: 'Ilha de Man',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['IM', 'IMN'],
    countryCode: '+44-1624',
  },
  Israel: {
    nameUS: 'Israel',
    nameBR: ' Israel',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['IL', 'ISR'],
    countryCode: '+972',
  },
  Italy: {
    nameUS: 'Italy',
    nameBR: 'Itália',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['IT', 'ITA'],
    countryCode: '+39',
  },
  'Ivory Coast': {
    nameUS: 'Ivory Coast',
    nameBR: 'Costa do Marfim',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['CI', 'CIV'],
    countryCode: '+225',
  },
  Jamaica: {
    nameUS: 'Jamaica',
    nameBR: 'Jamaica',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['JM', 'JAM'],
    countryCode: '+1-876',
  },
  Japan: {
    nameUS: 'Japan',
    nameBR: 'Japão',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['JP', 'JPN'],
    countryCode: '+81',
  },
  Jersey: {
    nameUS: 'Jersey',
    nameBR: 'Jersey',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['JE', 'JEY'],
    countryCode: '+44-1534',
  },
  Jordan: {
    nameUS: 'Jordan',
    nameBR: 'Jordânia',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['JO', 'JOR'],
    countryCode: '+962',
  },
  Kazakhstan: {
    nameUS: 'Kazakhstan',
    nameBR: 'Cazaquistão',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['KZ', 'KAZ'],
    countryCode: '+7',
  },
  Kenya: {
    nameUS: 'Kenya',
    nameBR: 'Quênia',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['KE', 'KEN'],
    countryCode: '+254',
  },
  Kiribati: {
    nameUS: 'Kiribati',
    nameBR: 'Kiribati',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['KI', 'KIR'],
    countryCode: '+686',
  },
  Kosovo: {
    nameUS: 'Kosovo',
    nameBR: 'Kosovo',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['XK', 'XKX'],
    countryCode: '+383',
  },
  Kuwait: {
    nameUS: 'Kuwait',
    nameBR: 'Kuwait',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['KW', 'KWT'],
    countryCode: '+965',
  },
  Kyrgyzstan: {
    nameUS: 'Kyrgyzstan',
    nameBR: 'Quirguistão',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['KG', 'KGZ'],
    countryCode: '+996',
  },
  Laos: {
    nameUS: 'Laos',
    nameBR: 'Laos',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['LA', 'LAO'],
    countryCode: '+856',
  },
  Latvia: {
    nameUS: 'Latvia',
    nameBR: 'Letônia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['LV', 'LVA'],
    countryCode: '+371',
  },
  Lebanon: {
    nameUS: 'Lebanon',
    nameBR: 'Líbano',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['LB', 'LBN'],
    countryCode: '+961',
  },
  Lesotho: {
    nameUS: 'Lesotho',
    nameBR: 'Lesoto',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['LS', 'LSO'],
    countryCode: '+266',
  },
  Liberia: {
    nameUS: 'Liberia',
    nameBR: 'Libéria',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['LR', 'LBR'],
    countryCode: '+231',
  },
  Libya: {
    nameUS: 'Libya',
    nameBR: 'Líbia',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['LY', 'LBY'],
    countryCode: '+218',
  },
  Liechtenstein: {
    nameUS: 'Liechtenstein',
    nameBR: 'Liechtenstein',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['LI', 'LIE'],
    countryCode: '+423',
  },
  Lithuania: {
    nameUS: 'Lithuania',
    nameBR: 'Lituânia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['LT', 'LTU'],
    countryCode: '+370',
  },
  Luxembourg: {
    nameUS: 'Luxembourg',
    nameBR: 'Luxemburgo',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['LU', 'LUX'],
    countryCode: '+352',
  },
  Macau: {
    nameUS: 'Macau',
    nameBR: 'Macau',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['MO', 'MAC'],
    countryCode: '+853',
  },
  Macedonia: {
    nameUS: 'Macedonia',
    nameBR: 'República da Macedônia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['MK', 'MKD'],
    countryCode: '+389',
  },
  Madagascar: {
    nameUS: 'Madagascar',
    nameBR: 'Madagascar',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['MG', 'MDG'],
    countryCode: '+261',
  },
  Malawi: {
    nameUS: 'Malawi',
    nameBR: 'Malawi',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['MW', 'MWI'],
    countryCode: '+265',
  },
  Malaysia: {
    nameUS: 'Malaysia',
    nameBR: 'Malásia',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['MY', 'MYS'],
    countryCode: '+60',
  },
  Maldives: {
    nameUS: 'Maldives',
    nameBR: 'Maldivas',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['MV', 'MDV'],
    countryCode: '+960',
  },
  Mali: {
    nameUS: 'Mali',
    nameBR: 'Mali',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['ML', 'MLI'],
    countryCode: '+223',
  },
  Malta: {
    nameUS: 'Malta',
    nameBR: 'Malta',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['MT', 'MLT'],
    countryCode: '+356',
  },
  'Marshall Islands': {
    nameUS: 'Marshall Islands',
    nameBR: 'Ilhas Marshall',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['MH', 'MHL'],
    countryCode: '+692',
  },
  Mauritania: {
    nameUS: 'Mauritania',
    nameBR: 'Mauritânia',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['MR', 'MRT'],
    countryCode: '+222',
  },
  Mauritius: {
    nameUS: 'Mauritius',
    nameBR: 'Maurícia',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['MU', 'MUS'],
    countryCode: '+230',
  },
  Mayotte: {
    nameUS: 'Mayotte',
    nameBR: 'Reunião',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['YT', 'MYT'],
    countryCode: '+262',
  },
  Mexico: {
    nameUS: 'Mexico',
    nameBR: 'México',
    continentUS: 'North America',
    continentBR: 'América do Norte',
    initials: ['MX', 'MEX'],
    countryCode: '+52',
  },
  Micronesia: {
    nameUS: 'Micronesia',
    nameBR: 'Estados Federados da Micronésia',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['FM', 'FSM'],
    countryCode: '+691',
  },
  Moldova: {
    nameUS: 'Moldova',
    nameBR: 'Moldávia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['MD', 'MDA'],
    countryCode: '+373',
  },
  Monaco: {
    nameUS: 'Monaco',
    nameBR: 'Mônaco',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['MC', 'MCO'],
    countryCode: '+377',
  },
  Mongolia: {
    nameUS: 'Mongolia',
    nameBR: 'Mongólia',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['MN', 'MNG'],
    countryCode: '+976',
  },
  Montenegro: {
    nameUS: 'Montenegro',
    nameBR: 'Montenegro',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['ME', 'MNE'],
    countryCode: '+382',
  },
  Montserrat: {
    nameUS: 'Montserrat',
    nameBR: 'Montserrat',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['MS', 'MSR'],
    countryCode: '+1-664',
  },
  Morocco: {
    nameUS: 'Morocco',
    nameBR: 'Marrocos',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['MA', 'MAR'],
    countryCode: '+212',
  },
  Mozambique: {
    nameUS: 'Mozambique',
    nameBR: 'Moçambique',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['MZ', 'MOZ'],
    countryCode: '+258',
  },
  Myanmar: {
    nameUS: 'Myanmar',
    nameBR: 'Myanmar',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['MM', 'MMR'],
    countryCode: '+95',
  },
  Namibia: {
    nameUS: 'Namibia',
    nameBR: 'Namíbia',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['NA', 'NAM'],
    countryCode: '+264',
  },
  Nauru: {
    nameUS: 'Nauru',
    nameBR: 'Nauru',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['NR', 'NRU'],
    countryCode: '+674',
  },
  Nepal: {
    nameUS: 'Nepal',
    nameBR: 'Nepal',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['NP', 'NPL'],
    countryCode: '+977',
  },
  Netherlands: {
    nameUS: 'Netherlands',
    nameBR: 'Países Baixos',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['NL', 'NLD'],
    countryCode: '+31',
  },
  'Netherlands Antilles': {
    nameUS: 'Netherlands Antilles',
    nameBR: 'Antilhas Holandesas',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['AN', 'ANT'],
    countryCode: '+599',
  },
  'New Caledonia': {
    nameUS: 'New Caledonia',
    nameBR: 'Nova Caledônia',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['NC', 'NCL'],
    countryCode: '+687',
  },
  'New Zealand': {
    nameUS: 'New Zealand',
    nameBR: 'Nova Zelândia',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['NZ', 'NZL'],
    countryCode: '+64',
  },
  Nicaragua: {
    nameUS: 'Nicaragua',
    nameBR: 'Nicarágua',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['NI', 'NIC'],
    countryCode: '+505',
  },
  Niger: {
    nameUS: 'Niger',
    nameBR: 'Níger',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['NE', 'NER'],
    countryCode: '+227',
  },
  Nigeria: {
    nameUS: 'Nigeria',
    nameBR: 'Nigéria',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['NG', 'NGA'],
    countryCode: '+234',
  },
  Niue: {
    nameUS: 'Niue',
    nameBR: 'Niue',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['NU', 'NIU'],
    countryCode: '+683',
  },
  'North Korea': {
    nameUS: 'North Korea',
    nameBR: 'Coreia do Norte',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['KP', 'PRK'],
    countryCode: '+850',
  },
  'Northern Mariana Islands': {
    nameUS: 'Northern Mariana Islands',
    nameBR: 'Ilhas Marianas do Norte',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['MP', 'MNP'],
    countryCode: '+1-670',
  },
  Norway: {
    nameUS: 'Norway',
    nameBR: 'Noruega',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['NO', 'NOR'],
    countryCode: '+47',
  },
  Oman: {
    nameUS: 'Oman',
    nameBR: 'Omã',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['OM', 'OMN'],
    countryCode: '+968',
  },
  Pakistan: {
    nameUS: 'Pakistan',
    nameBR: 'Paquistão',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['PK', 'PAK'],
    countryCode: '+92',
  },
  Palau: {
    nameUS: 'Palau',
    nameBR: 'Palau',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['PW', 'PLW'],
    countryCode: '+680',
  },
  Palestine: {
    nameUS: 'Palestine',
    nameBR: 'Palestina',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['PS', 'PSE'],
    countryCode: '+970',
  },
  Panama: {
    nameUS: 'Panama',
    nameBR: 'Panamá',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['PA', 'PAN'],
    countryCode: '+507',
  },
  'Papua New Guinea': {
    nameUS: 'Papua New Guinea',
    nameBR: 'Papua-Nova Guiné',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['PG', 'PNG'],
    countryCode: '+675',
  },
  Paraguay: {
    nameUS: 'Paraguay',
    nameBR: 'Paraguai',
    continentUS: 'South America',
    continentBR: 'América do Sul',
    initials: ['PY', 'PRY'],
    countryCode: '+595',
  },
  Peru: {
    nameUS: 'Peru',
    nameBR: 'Peru',
    continentUS: 'South America',
    continentBR: 'América do Sul',
    initials: ['PE', 'PER'],
    countryCode: '+51',
  },
  Philippines: {
    nameUS: 'Philippines',
    nameBR: 'Filipinas',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['PH', 'PHL'],
    countryCode: '+63',
  },
  Pitcairn: {
    nameUS: 'Pitcairn',
    nameBR: 'Nova Zelândia',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['PN', 'PCN'],
    countryCode: '+64',
  },
  Poland: {
    nameUS: 'Poland',
    nameBR: 'Polônia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['PL', 'POL'],
    countryCode: '+48',
  },
  Portugal: {
    nameUS: 'Portugal',
    nameBR: 'Portugal',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['PT', 'PRT'],
    countryCode: '+351',
  },
  'Puerto Rico': {
    nameUS: 'Puerto Rico',
    nameBR: 'Porto Rico',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['PR', 'PRI'],
    countryCode: '+1-787 +1-939',
  },
  Qatar: {
    nameUS: 'Qatar',
    nameBR: 'Qatar',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['QA', 'QAT'],
    countryCode: '+974',
  },
  'Republic of the Congo': {
    nameUS: 'Republic of the Congo',
    nameBR: 'Congo-Brazzaville',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['CG', 'COG'],
    countryCode: '+242',
  },
  Reunion: {
    nameUS: 'Reunion',
    nameBR: 'Reunião',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['RE', 'REU'],
    countryCode: '+262',
  },
  Romania: {
    nameUS: 'Romania',
    nameBR: 'Romênia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['RO', 'ROU'],
    countryCode: '+40',
  },
  Russia: {
    nameUS: 'Russia',
    nameBR: 'Cazaquistão',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['RU', 'RUS'],
    countryCode: '+7',
  },
  Rwanda: {
    nameUS: 'Rwanda',
    nameBR: 'Ruanda',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['RW', 'RWA'],
    countryCode: '+250',
  },
  'Saint Barthelemy': {
    nameUS: 'Saint Barthelemy',
    nameBR: 'Guadalupe',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['BL', 'BLM'],
    countryCode: '+590',
  },
  'Saint Helena': {
    nameUS: 'Saint Helena',
    nameBR: 'Santa Helena (território)',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['SH', 'SHN'],
    countryCode: '+290',
  },
  'Saint Kitts and Nevis': {
    nameUS: 'Saint Kitts and Nevis',
    nameBR: 'São Cristóvão e Nevis',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['KN', 'KNA'],
    countryCode: '+1-869',
  },
  'Saint Lucia': {
    nameUS: 'Saint Lucia',
    nameBR: 'Santa Lúcia',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['LC', 'LCA'],
    countryCode: '+1-758',
  },
  'Saint Martin': {
    nameUS: 'Saint Martin',
    nameBR: 'Guadalupe',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['MF', 'MAF'],
    countryCode: '+590',
  },
  'Saint Pierre and Miquelon': {
    nameUS: 'Saint Pierre and Miquelon',
    nameBR: 'Saint-Pierre e Miquelon',
    continentUS: 'North America',
    continentBR: 'América do Norte',
    initials: ['PM', 'SPM'],
    countryCode: '+508',
  },
  'Saint Vincent and the Grenadines': {
    nameUS: 'Saint Vincent and the Grenadines',
    nameBR: 'São Vicente e Granadinas',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['VC', 'VCT'],
    countryCode: '+1-784',
  },
  Samoa: {
    nameUS: 'Samoa',
    nameBR: 'Samoa',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['WS', 'WSM'],
    countryCode: '+685',
  },
  'San Marino': {
    nameUS: 'San Marino',
    nameBR: 'São Marinho',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['SM', 'SMR'],
    countryCode: '+378',
  },
  'Sao Tome and Principe': {
    nameUS: 'Sao Tome and Principe',
    nameBR: 'São Tomé e Príncipe',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['ST', 'STP'],
    countryCode: '+239',
  },
  'Saudi Arabia': {
    nameUS: 'Saudi Arabia',
    nameBR: 'Arábia Saudita',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['SA', 'SAU'],
    countryCode: '+966',
  },
  Senegal: {
    nameUS: 'Senegal',
    nameBR: 'Senegal',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['SN', 'SEN'],
    countryCode: '+221',
  },
  Serbia: {
    nameUS: 'Serbia',
    nameBR: 'Sérvia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['RS', 'SRB'],
    countryCode: '+381',
  },
  Seychelles: {
    nameUS: 'Seychelles',
    nameBR: 'Seicheles',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['SC', 'SYC'],
    countryCode: '+248',
  },
  'Sierra Leone': {
    nameUS: 'Sierra Leone',
    nameBR: 'Serra Leoa',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['SL', 'SLE'],
    countryCode: '+232',
  },
  Singapore: {
    nameUS: 'Singapore',
    nameBR: 'Singapura',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['SG', 'SGP'],
    countryCode: '+65',
  },
  'Sint Maarten': {
    nameUS: 'Sint Maarten',
    nameBR: 'São Martinho',
    continentUS: 'North America',
    continentBR: 'América do Norte',
    initials: ['SX', 'SXM'],
    countryCode: '+1-721',
  },
  Slovakia: {
    nameUS: 'Slovakia',
    nameBR: 'Eslováquia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['SK', 'SVK'],
    countryCode: '+421',
  },
  Slovenia: {
    nameUS: 'Slovenia',
    nameBR: 'Eslovénia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['SI', 'SVN'],
    countryCode: '+386',
  },
  'Solomon Islands': {
    nameUS: 'Solomon Islands',
    nameBR: 'Ilhas Salomão',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['SB', 'SLB'],
    countryCode: '+677',
  },
  Somalia: {
    nameUS: 'Somalia',
    nameBR: 'Somália',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['SO', 'SOM'],
    countryCode: '+252',
  },
  'South Africa': {
    nameUS: 'South Africa',
    nameBR: 'África do Sul',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['ZA', 'ZAF'],
    countryCode: '+27',
  },
  'South Korea': {
    nameUS: 'South Korea',
    nameBR: 'Coreia do Sul',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['KR', 'KOR'],
    countryCode: '+82',
  },
  'South Sudan': {
    nameUS: 'South Sudan',
    nameBR: 'Sudão do Sul',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['SS', 'SSD'],
    countryCode: '+211',
  },
  Spain: {
    nameUS: 'Spain',
    nameBR: 'Espanha',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['ES', 'ESP'],
    countryCode: '+34',
  },
  'Sri Lanka': {
    nameUS: 'Sri Lanka',
    nameBR: 'Sri Lanka',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['LK', 'LKA'],
    countryCode: '+94',
  },
  Sudan: {
    nameUS: 'Sudan',
    nameBR: 'Sudão',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['SD', 'SDN'],
    countryCode: '+249',
  },
  Suriname: {
    nameUS: 'Suriname',
    nameBR: 'Suriname',
    continentUS: 'South America',
    continentBR: 'América do Sul',
    initials: ['SR', 'SUR'],
    countryCode: '+597',
  },
  'Svalbard and Jan Mayen': {
    nameUS: 'Svalbard and Jan Mayen',
    nameBR: 'Noruega',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['SJ', 'SJM'],
    countryCode: '+47',
  },
  Swaziland: {
    nameUS: 'Swaziland',
    nameBR: 'Suazilândia',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['SZ', 'SWZ'],
    countryCode: '+268',
  },
  Sweden: {
    nameUS: 'Sweden',
    nameBR: 'Suécia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['SE', 'SWE'],
    countryCode: '+46',
  },
  Switzerland: {
    nameUS: 'Switzerland',
    nameBR: 'Suíça',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['CH', 'CHE'],
    countryCode: '+41',
  },
  Syria: {
    nameUS: 'Syria',
    nameBR: 'Síria',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['SY', 'SYR'],
    countryCode: '+963',
  },
  Taiwan: {
    nameUS: 'Taiwan',
    nameBR: 'República da China',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['TW', 'TWN'],
    countryCode: '+886',
  },
  Tajikistan: {
    nameUS: 'Tajikistan',
    nameBR: 'Tadjiquistão',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['TJ', 'TJK'],
    countryCode: '+992',
  },
  Tanzania: {
    nameUS: 'Tanzania',
    nameBR: 'Tanzânia',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['TZ', 'TZA'],
    countryCode: '+255',
  },
  Thailand: {
    nameUS: 'Thailand',
    nameBR: 'Tailândia',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['TH', 'THA'],
    countryCode: '+66',
  },
  Togo: {
    nameUS: 'Togo',
    nameBR: 'Togo',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['TG', 'TGO'],
    countryCode: '+228',
  },
  Tokelau: {
    nameUS: 'Tokelau',
    nameBR: 'Tokelau',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['TK', 'TKL'],
    countryCode: '+690',
  },
  Tonga: {
    nameUS: 'Tonga',
    nameBR: 'Tonga',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['TO', 'TON'],
    countryCode: '+676',
  },
  'Trinidad and Tobago': {
    nameUS: 'Trinidad and Tobago',
    nameBR: 'Trinidad e Tobago',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['TT', 'TTO'],
    countryCode: '+1-868',
  },
  Tunisia: {
    nameUS: 'Tunisia',
    nameBR: 'Tunísia',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['TN', 'TUN'],
    countryCode: '+216',
  },
  Turkey: {
    nameUS: 'Turkey',
    nameBR: 'Turquia',
    continentUS: 'Asia, Europe',
    continentBR: 'Ásia, Europa',
    initials: ['TR', 'TUR'],
    countryCode: '+90',
  },
  Turkmenistan: {
    nameUS: 'Turkmenistan',
    nameBR: 'Turquemenistão',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['TM', 'TKM'],
    countryCode: '+993',
  },
  'Turks and Caicos Islands': {
    nameUS: 'Turks and Caicos Islands',
    nameBR: 'Turcas e Caicos',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['TC', 'TCA'],
    countryCode: '+1-649',
  },
  Tuvalu: {
    nameUS: 'Tuvalu',
    nameBR: 'Tuvalu',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['TV', 'TUV'],
    countryCode: '+688',
  },
  'U.S. Virgin Islands': {
    nameUS: 'U.S. Virgin Islands',
    nameBR: 'Ilhas Virgens Americanas',
    continentUS: 'Central America',
    continentBR: 'América Central',
    initials: ['VI', 'VIR'],
    countryCode: '+1-340',
  },
  Uganda: {
    nameUS: 'Uganda',
    nameBR: 'Uganda',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['UG', 'UGA'],
    countryCode: '+256',
  },
  Ukraine: {
    nameUS: 'Ukraine',
    nameBR: 'Ucrânia',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['UA', 'UKR'],
    countryCode: '+380',
  },
  'United Arab Emirates': {
    nameUS: 'United Arab Emirates',
    nameBR: 'Emirados Árabes Unidos',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['AE', 'ARE'],
    countryCode: '+971',
  },
  'United Kingdom': {
    nameUS: 'United Kingdom',
    nameBR: 'Reino Unido',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['GB', 'GBR'],
    countryCode: '+44',
  },
  'United States': {
    nameUS: 'United States',
    nameBR: 'Estados Unidos',
    continentUS: 'North America',
    continentBR: 'América do Norte',
    initials: ['US', 'USA'],
    countryCode: '+1',
  },
  Uruguay: {
    nameUS: 'Uruguay',
    nameBR: 'Uruguai',
    continentUS: 'South America',
    continentBR: 'América do Sul',
    initials: ['UY', 'URY'],
    countryCode: '+598',
  },
  Uzbekistan: {
    nameUS: 'Uzbekistan',
    nameBR: 'Uzbequistão',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['UZ', 'UZB'],
    countryCode: '+998',
  },
  Vanuatu: {
    nameUS: 'Vanuatu',
    nameBR: 'Vanuatu',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['VU', 'VUT'],
    countryCode: '+678',
  },
  Vatican: {
    nameUS: 'Vatican',
    nameBR: 'Vaticano',
    continentUS: 'Europe',
    continentBR: 'Europa',
    initials: ['VA', 'VAT'],
    countryCode: '+379',
  },
  Venezuela: {
    nameUS: 'Venezuela',
    nameBR: 'Venezuela',
    continentUS: 'South America',
    continentBR: 'América do Sul',
    initials: ['VE', 'VEN'],
    countryCode: '+58',
  },
  Vietnam: {
    nameUS: 'Vietnam',
    nameBR: 'Vietnã',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['VN', 'VNM'],
    countryCode: '+84',
  },
  'Wallis and Futuna': {
    nameUS: 'Wallis and Futuna',
    nameBR: 'Wallis e Futuna',
    continentUS: 'Oceania',
    continentBR: 'Oceania',
    initials: ['WF', 'WLF'],
    countryCode: '+681',
  },
  'Western Sahara': {
    nameUS: 'Western Sahara',
    nameBR: 'Marrocos',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['EH', 'ESH'],
    countryCode: '+212',
  },
  Yemen: {
    nameUS: 'Yemen',
    nameBR: 'Iêmen',
    continentUS: 'Asia',
    continentBR: 'Ásia',
    initials: ['YE', 'YEM'],
    countryCode: '+967',
  },
  Zambia: {
    nameUS: 'Zambia',
    nameBR: 'Zâmbia',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['ZM', 'ZMB'],
    countryCode: '+260',
  },
  Zimbabwe: {
    nameUS: 'Zimbabwe',
    nameBR: 'Zimbábue',
    continentUS: 'Africa',
    continentBR: 'África',
    initials: ['ZW', 'ZWE'],
    countryCode: '+263',
  },
};

export default COUNTRIES;
